Repository Mercado-Lite/Mercado-Lite, pull requests merged in 2022-10, with the labels that each got.

#5 First commit
  .gitattributes
  .gitignore
  css/pg3.css
  img/img-test.png
  index.html
Labels: good first issue

#6 Add products page
  css/style.css
  img/airpod-glasses.jpg
  img/airtag-socks.jpg
  img/blind-glasses.jpg
  img/food-funnel.jpg
  img/gas-price-shield.jpg
  img/mask-spenders.jpg
  img/mirror-selfie.jpg
  products.html
Labels: enhancement

#7 feat: item details pages
  airpod-glasses.html
  airtag-socks.html
  blind-glasses.html
  css/pg3-reset.css
  css/pg3.css
  gas-price-shield.html
  img/dhruv-N9UuFddi7hs-unsplash.jpg
  index.html
  mask-spenders.html
  mirror-selfie.html
  products.html
Labels: enhancement

#8 fix: fix cart icon
  airpod-glasses.html
  airtag-socks.html
  blind-glasses.html
  css/pg3.css
  gas-price-shield.html
  img/dhruv-N9UuFddi7hs-unsplash.jpg
  img/img-test.png
  mask-spenders.html
  mirror-selfie.html
Labels: bug

#9 fix: fix icons
  airpod-glasses.html
  airtag-socks.html
  blind-glasses.html
  css/pg3.css
  gas-price-shield.html
  mirror-selfie.html
Labels: bug

#10 fix: fix bugs
  mask-spenders.html
Labels: bug

#11 fix: fix icons bug
  airpod-glasses.html
  airtag-socks.html
  blind-glasses.html
  css/pg3.css
  gas-price-shield.html
  mask-spenders.html
  mirror-selfie.html
Labels: bug

#18 fix: bugs
  airpod-glasses.html
  airtag-socks.html
  blind-glasses.html
  css/pg3.css
  gas-price-shield.html
  hf-style.css
  mask-spenders.html
  mirror-selfie.html
  products.html
Labels: bug
